# Generated by Django 4.2.13 on 2024-07-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_reaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='question.question'),
        ),
    ]
